name: Build and Deploy Branch
on:
  workflow_call:
    inputs:
      appname:
        required: true
        type: string
      helm_name:
        required: true
        type: string
      helm_timeout:
        default: "120s"
        required: false
        type: string
      dev_ns:
        required: true
        type: string
      stg_ns:
        required: true
        type: string
      prod_ns:
        required: true
        type: string
      use_ssm:
        default: true
        required: false
        type: boolean
      simple_deploy:
        default: false
        required: false
        type: boolean
      dockerfile:
        default: "Dockerfile"
        required: false
        type: string
      release:
        default: false
        required: false
        type: boolean
      eks_cluster:
        default: potato-pie
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_NAME: ${{ inputs.appname }}
  HELM_NAME: ${{ inputs.helm_name }}
  HELM_TIMEOUT: ${{ inputs.helm_timeout }}
  DEV_NS: ${{ inputs.dev_ns }}
  STG_NS: ${{ inputs.stg_ns }}
  PROD_NS: ${{ inputs.prod_ns }}
  SIMPLE_DEPLOY: ${{ inputs.simple_deploy }}
  USE_SSM: ${{ inputs.use_ssm }}
  DOCKERFILE: ${{ inputs.dockerfile }}
  SHOULD_RELEASE: ${{ inputs.release }}

jobs:
  Build:
    uses: ./.github/workflows/build_branch.yaml
    with:
      dockerfile: ${{ inputs.dockerfile }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Deploy:
    uses: ./.github/workflows/deploy_branch.yaml
    needs: [Build]
    with:
      appname: ${{ inputs.appname }}
      helm_name: ${{ inputs.helm_name }}
      helm_timeout: ${{ inputs.helm_timeout }}
      dev_ns: ${{ inputs.dev_ns }}
      stg_ns: ${{ inputs.stg_ns }}
      prod_ns: ${{ inputs.prod_ns }}
      use_ssm: ${{ inputs.use_ssm }}
      simple_deploy: ${{ inputs.simple_deploy }}
      release: ${{ inputs.release }}
      eks_cluster: ${{ inputs.eks_cluster }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  