name: CDK Deploy

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        description: runner type
        type: string
        default: ubuntu-latest
      aws_account_id: 
        required: true
        description: AWS account ID
        type: string
      aws_region:
        required: false
        type: string
        description: AWS region
        default: us-east-1
      subtree_repo:
        required: false
        type: string
        default: FirstStreet/fs-deployment-pipeline
      subtree_path:
        required: true
        type: string
        default: deployments
      subtree_ref:
        required: false
        type: string
        default: main
      deploy_service_account_with_policy:
        required: false
        default: false
        description: deploy policy from file and add EKS service account to use the policy
        type: boolean
      # params for deploy_service_account_with_policy
      eks_service_account_name:
        required: false
        type: string
        description: EKS service account name
      policy_file:
        required: false
        type: string
        description: IAM policy file path
      eks_cluster:
        required: false
        type: string
        description: EKS cluster name
      namespace:
        required: false
        type: string
        description: EKS namespace
    secrets:
      SUBTREE_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  Build:
    runs-on: ${{ inputs.runs_on }}
    env:
      REGION: ${{ inputs.aws_region }}
      AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
      SUBTREE_REPO: ${{ inputs.subtree_repo }}
      SUBTREE_PATH: ${{ inputs.subtree_path }}
      SUBTREE_REF: ${{ inputs.subtree_ref }}
      EKS_SERVICE_ACCOUNT_NAME: ${{ inputs.eks_service_account_name }}
      POLICY_FILE: ${{ inputs.policy_file }}
      EKS_CLUSTER: ${{ inputs.eks_cluster }}
      NAMESPACE: ${{ inputs.namespace }}
      DEPLOY_SERVICE_ACCOUNT_WITH_POLICY: ${{ inputs.deploy_service_account_with_policy}}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: checkout subtree
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.subtree_repo }}
          token: ${{ secrets.SUBTREE_TOKEN }}
          ref: ${{ inputs.subtree_ref }}
          path: ${{ inputs.subtree_path }}

          
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}
            
      - uses: azure/setup-helm@v3

      - name: Prepare eks environment
        if: ${{ inputs.deploy_service_account_with_policy }}
        run: |
            aws eks update-kubeconfig --name ${{ inputs.eks_cluster }}
            
      - name: Deploy EKS service account with policy
        if: ${{ inputs.deploy_service_account_with_policy }}
        run: |
            ls -la
            sh ./eks-role/create_role_for_eks.sh -policy ${{ env.POLICY_FILE }} -cluster ${{ env.EKS_CLUSTER }} -namespace ${{ env.NAMESPACE }} -service-account ${{ env.EKS_SERVICE_ACCOUNT_NAME }}
