name: Deploy With AWS role
on:
  workflow_call:
    inputs:
      aws_account_id:
        required: true
        type: string
      appname:
        required: true
        type: string
      helm_name:
        required: true
        type: string
      helm_timeout:
        default: "300s"
        required: false
        type: string
      namespace:
        required: true
        type: string
      helm_config:
        required: true
        type: string
      use_ssm:
        default: true
        required: false
        type: boolean
      simple_deploy:
        default: false
        required: false
        type: boolean
      eks_cluster:
        default: potato-pie
        required: false
        type: string

env:
  APP_NAME: ${{ inputs.appname }}
  AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
  HELM_NAME: ${{ inputs.helm_name }}
  HELM_TIMEOUT: ${{ inputs.helm_timeout }}
  NAMESPACE: ${{ inputs.namespace }}
  HELM_CONFIG: ${{ inputs.helm_config }}
  SIMPLE_DEPLOY: ${{ inputs.simple_deploy }}
  USE_SSM: ${{ inputs.use_ssm }}
  EKS_CLUSTER: ${{ inputs.eks_cluster }}

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: aws
    # environment: ${{needs.Build.outputs.appenv}}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deployment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

        run: |
          echo "VALUES=_k/${APP_NAME}/values-${HELM_CONFIG}.yaml" >> $GITHUB_ENV
          echo "CONF_ENV=${HELM_CONFIG}" >> $GITHUB_ENV
          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.2"

      - uses: actions/setup-node@v3
      - uses: azure/setup-helm@v3
        with:
          version: "v3.6.0" # default is latest stable

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short=4 HEAD)" >> $GITHUB_OUTPUT
        
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          role-to-assume: "arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/GitHubAction-AssumeRoleWithAction"
          role-session-name: GithubActions-${{ github.event.repository.name }}-${{ inputs.helm_name }}-${{ inputs.helm_config }}-${{ steps.vars.outputs.sha_short }}
          aws-region: us-east-1

      - name: Deploying Namespace
        run: |
          echo $NAMESPACE
          echo $VALUES

      - name: Deploy
        run: |
          aws eks update-kubeconfig --name ${{ inputs.eks_cluster }}
          
          kubectl get svc
          
          if [[ $USE_SSM == true ]]; then
            helm plugin remove ssm || true
            helm plugin add https://github.com/seripap/helm-ssm || true
            helm ssm -f $VALUES
          fi

          sed -i "s/^appVersion:.*$/appVersion: \"$(git describe)\"/" _k/$APP_NAME/Chart.yaml

          if [[ $SIMPLE_DEPLOY == true ]]; then
            echo "Starting upgrade"
            helm upgrade $HELM_NAME _k/$APP_NAME --install --namespace $NAMESPACE --set app.image.tag=sha-$GITHUB_SHA-$NAMESPACE -f $VALUES --wait --timeout $HELM_TIMEOUT --debug
          else
            helm upgrade $HELM_NAME _k/$APP_NAME --install --namespace $NAMESPACE --set app.image.tag=sha-$GITHUB_SHA-$NAMESPACE,app.config=$CONF_ENV,volume.path=$CONF_ENV.conf -f $VALUES --wait --timeout $HELM_TIMEOUT --debug
          fi
