name: Build and Deploy
on:
  workflow_call:
    inputs:
      appname:
        required: true
        type: string
      helm_name:
        required: true
        type: string
      namespace:
        required: true
        type: string
      helm_config:
        required: true
        type: string
      use_ssm:
        default: true
        required: false
        type: boolean
      simple_deploy:
        default: false
        required: false
        type: boolean
      dockerfile:
        default: "Dockerfile"
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_NAME: ${{ inputs.appname }}
  HELM_NAME: ${{ inputs.helm_name }}
  NAMESPACE: ${{ inputs.namespace }}
  HELM_CONFIG: ${{ inputs.helm_config }}
  SIMPLE_DEPLOY: ${{ inputs.simple_deploy }}
  USE_SSM: ${{ inputs.use_ssm }}
  DOCKERFILE: ${{ inputs.dockerfile }}

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # outputs:
    #   appenv: ${{ steps.setappenv.outputs.env }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ env.NAMESPACE }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}-${{ env.NAMESPACE }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long,suffix=-${{ env.NAMESPACE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ env.DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # This only works for pub repos
      # - id: setappenv
      #   run: |
      #     if [[ "$GITHUB_REF_NAME" == *"develop"* ]]; then
      #       echo "::set-output name=DEPLOY_ENV::development"
      #     elif [[ "$GITHUB_REF_NAME" == *"master"* ]]; then
      #       echo "::set-output name=DEPLOY_ENV::production"
      #     fi

  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    # environment: ${{needs.Build.outputs.appenv}}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare deployment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

        run: |
          echo "VALUES=_k/${HELM_NAME}/values-${HELM_CONFIG}.yaml" >> $GITHUB_ENV
          echo "CONF_ENV=${HELM_CONFIG}" >> $GITHUB_ENV
          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v1
        with:
          version: "v1.22.4"

      - uses: actions/setup-node@v2
      - uses: azure/setup-helm@v1
        with:
          version: "v3.6.0" # default is latest stable

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploying Namespace
        run: |
          echo $NAMESPACE
          echo $VALUES

      - name: Deploy
        run: |
          aws eks update-kubeconfig --name fsf-prod
          if [[ $USE_SSM == true ]]; then
            helm plugin remove ssm || true
            helm plugin add https://github.com/seripap/helm-ssm || true
            helm ssm -f $VALUES
          fi

          sed -i "s/^appVersion:.*$/appVersion: \"$(git describe)\"/" _k/$APP_NAME/Chart.yaml

          if [[ $SIMPLE_DEPLOY == true ]]; then
            helm upgrade $APP_NAME _k/$APP_NAME --install --namespace $NAMESPACE --set app.image.tag=sha-$GITHUB_SHA-$NAMESPACE -f $VALUES --wait --timeout 300s --debug
          else
            helm upgrade $APP_NAME _k/$APP_NAME --install --namespace $NAMESPACE --set app.config=$CONF_ENV,volume.path=$CONF_ENV.conf,app.image.tag=sha-$GITHUB_SHA-$NAMESPACE -f $VALUES --wait --timeout 300s --debug
          fi
